# Practical 1: Getting Started with Data
## 6COM2005 Data Mining and Visualisation

In this practical you will:
- Use Git and GitHub to get and save your work.
- Load a dataset into a pandas DataFrame and inspect its objects and attributes.
- Identify attribute types and the class label.
- Ask simple questions of the data with pandas.
- Choose and draw the right chart for a question (bar, histogram, scatter).
- See why we must always plot the data (Anscombe's quartet).

## Part 1: Load the Data

In [1]:
# 1.1 Import pandas and matplotlib.
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# 1.2 Load `penguins.csv` into a DataFrame called `df`.
df = pd.read_csv("penguins.csv")
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [4]:
# 1.3 Show the first 5 rows and the shape (rows, columns) of the data.
print(df.shape)
df.head()

(344, 8)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [6]:
# 1.4 Show the column names and their data types.
df.dtypes

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
year                   int64
dtype: object

<pre>
Commit and push your work:

git status
git add .
git commit -m "Part 1: loaded the penguins dataset"
git push
</pre>

## Part 2: Objects and Attributes

**2.1 In a markdown cell: what does one row (object) describe? Which column is the class label?**

*Write your answer here.*

**2.2 In a markdown table, give the type of each attribute: nominal, binary, ordinal, interval, or ratio.**

*Write your answer here.*

In [ ]:
# 2.3 Count how many penguins there are of each species and on each island.

In [ ]:
# 2.4 Count the missing values in each column.

In [ ]:
# 2.5 Remove the rows with missing values and save the result as `df_clean`. How many rows are left?

<pre>
Commit and push your work:

git status
git add .
git commit -m "Part 2: attribute types and missing values"
git push
</pre>

## Part 3: Ask Questions of the Data

In [ ]:
# 3.1 Select only the Gentoo penguins. How many are there?

In [ ]:
# 3.2 Calculate the mean body mass of each species.

In [ ]:
# 3.3 Make a table of species against island. Which species lives on all three islands?

**3.4 In a markdown cell: are tasks 3.1 to 3.3 data mining, or simple queries? Explain using the definition from Lecture 1.**

*Write your answer here.*

<pre>
Commit and push your work:

git status
git add .
git commit -m "Part 3: questions with pandas"
git push
</pre>

## Part 4: Visualise the Data

In [ ]:
# 4.1 Draw a bar chart of the number of penguins per species.

In [ ]:
# 4.2 Draw a histogram of flipper length with 20 bins. Label the axes.

In [ ]:
# 4.3 Draw a scatter plot of bill length (x) against bill depth (y), with one colour per species and a legend.

**4.4 In a markdown cell: look at your histogram and scatter plot. What do you notice? Which data mining task could use these patterns?**

*Write your answer here.*

<pre>
Commit and push your work:

git status
git add .
git commit -m "Part 4: charts"
git push
</pre>

## Part 5: Always Plot Your Data

In [ ]:
# 5.1 Load `anscombe.csv`. For each dataset (I to IV), calculate the mean and variance of x and y.

In [ ]:
# 5.2 Draw the four datasets as four scatter plots side by side.

**5.3 In a markdown cell: what is the lesson of this part?**

*Write your answer here.*

<pre>
Commit and push your work:

git status
git add .
git commit -m "Part 5: Anscombe's quartet"
git push
</pre>